import { spawnSync } from "node:child_process";
import { mkdirSync } from "node:fs";
mkdirSync("out", { recursive: true });
function run(cmd, args) {
  const r = spawnSync(cmd, args, { stdio: "inherit" });
  if (r.error) throw r.error;
  if (r.status !== 0) process.exit(r.status ?? 1);
}
// Render a visually lossless intermediate, then mux an explicit silent stereo
// AAC stream and normalize exhibition playback metadata/rate control.
run("pnpm", [
  "exec",
  "remotion",
  "render",
  "src/index.ts",
  "TeratecInstitutional",
  "out/picture.mp4",
  "--codec=h264",
  "--crf=10",
  "--image-format=png",
  "--pixel-format=yuv420p",
  "--concurrency=4",
]);
run("ffmpeg", [
  "-y",
  "-i",
  "out/picture.mp4",
  "-f",
  "lavfi",
  "-i",
  "anullsrc=channel_layout=stereo:sample_rate=48000",
  "-map",
  "0:v:0",
  "-map",
  "1:a:0",
  "-c:v",
  "libx264",
  "-preset",
  "medium",
  "-profile:v",
  "high",
  "-vf",
  "scale=in_range=auto:out_range=limited,format=yuv420p,setparams=range=limited:color_primaries=bt709:color_trc=bt709:colorspace=bt709,sidedata=delete:type=ICC_PROFILE",
  "-color_range",
  "tv",
  "-pix_fmt",
  "yuv420p",
  "-r",
  "30",
  "-b:v",
  "16M",
  "-minrate",
  "16M",
  "-maxrate",
  "16M",
  "-bufsize",
  "32M",
  "-x264-params",
  "nal-hrd=cbr:force-cfr=1:aq-mode=3",
  "-color_primaries",
  "bt709",
  "-color_trc",
  "bt709",
  "-colorspace",
  "bt709",
  "-c:a",
  "aac",
  "-b:a",
  "192k",
  "-ar",
  "48000",
  "-ac",
  "2",
  "-t",
  "150",
  "-movflags",
  "+faststart",
  "out/ZenML_Teratec2026_Institutional_EN_v15.mp4",
]);
